In [1]:
import pandas as pd

In [7]:
may18 = pd.read_csv('raw_data/201805-citibike-tripdata.csv') 
jun18 = pd.read_csv('raw_data/201806-citibike-tripdata.csv') 


nov18 = pd.read_csv('raw_data/201811-citibike-tripdata.csv') 
dec18 = pd.read_csv('raw_data/201812-citibike-tripdata.csv')

In [ ]:
cold = [nov18,dec18]
warm = [may18, jun18]

cold18 = pd.concat(cold, axis = 0, ignore_index = True)
warm18 = pd.concat(warm, axis = 0, ignore_index = True)

In [16]:
cold18['weather'] = 'cold'
warm18['weather'] = 'warm'

weatherlist = [cold18,warm18]

In [17]:
alldata = pd.concat(weatherlist, axis = 0, ignore_index = True)

In [19]:
alldata.to_csv('alldata2018.csv')

In [18]:
alldata.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,weather
0,254,2018-11-01 00:00:12.9100,2018-11-01 00:04:27.3870,3522.0,37 St & 24 Ave,40.770148,-73.912094,3513.0,21 St & Hoyt Ave S,40.774645,-73.923706,34117,Subscriber,1992,1,cold
1,833,2018-11-01 00:00:16.3440,2018-11-01 00:14:09.4320,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,251.0,Mott St & Prince St,40.723180,-73.994800,32569,Subscriber,1986,2,cold
2,683,2018-11-01 00:00:17.6630,2018-11-01 00:11:40.9170,3405.0,5 St & 6 Ave,40.670484,-73.982090,3584.0,Eastern Pkwy & Franklin Ave,40.670777,-73.957680,15795,Subscriber,1985,1,cold
3,1840,2018-11-01 00:00:18.7970,2018-11-01 00:30:59.3050,3150.0,E 85 St & York Ave,40.775369,-73.948034,297.0,E 15 St & 3 Ave,40.734232,-73.986923,33290,Subscriber,1994,1,cold
4,1212,2018-11-01 00:00:47.3230,2018-11-01 00:20:59.8840,325.0,E 19 St & 3 Ave,40.736245,-73.984738,212.0,W 16 St & The High Line,40.743349,-74.006818,17411,Subscriber,1989,1,cold